services:
  - type: web
    name: whatsapp-gemini-bot
    env: node
    buildCommand: npm install
    startCommand: node index.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18